### ISSUE TITLE
Create executable Bash script

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#1]
To improve reproducibility, file `script.txt` should become a real executable Bash script (for instance `script.sh`).
The script could even be split into sub-scripts: `download_sgd_data.sh`, `create_database.sh`...

**Comment by Thibault-Poinsignon** [comment]
Script.txt was split into download_SGD_data.sh, download_SGD_readme.sh, schema_sceres.sql and import_SGD_data_to_tables.sql.
