### ISSUE TITLE
sqlitebrowser from bioconda is outdated

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#12]
[sqlitebrowser](https://anaconda.org/bioconda/sqlitebrowser) provided by bioconda is outdated (version 3.8.0) and required QT 4, not available in conda.

We need to install sqlitebrower [manually](https://sqlitebrowser.org/dl/) with `apt`

**Comment by pierrepo** [comment]
We should probably list apt requirements in an `apt.txt` file to later install these dependencies with:
```
grep -vE '^#' apt.txt | xargs sudo apt install -y
```

**Comment by Thibault-Poinsignon** [comment]
Good idea !
