### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#16]
Since we have to rename this repo (no middle `s` in `sceres_database`), maybe we could also change the `database` part into something more explicit. Why not:
- scere_mine ?
- scere_explore ?
- scere_view ?

What do you think @Thibault-Poinsignon ?

**Comment by Thibault-Poinsignon** [comment]
Do you mean in the readme ?

**Comment by pierrepo** [comment]
Nop. The name of your repo:
![image](https://user-images.githubusercontent.com/733861/107520548-d57c2b00-6bb1-11eb-9306-14eac951441e.png)

**Comment by Thibault-Poinsignon** [comment]
Ho ok ! You are right, I like scere_explore.

**Comment by pierrepo** [comment]
So let's go with `scere_explore` :mag_right:

**Comment by Thibault-Poinsignon** [comment]
Done, I will do a commit to correct `readme. md` and `schema_sceres.sql`.

**Comment by pierrepo** [comment]
Perfect. I cloned the repo with its new name
