### ISSUE TITLE
Plotly.express and matplotlib.pyplot version

### ISSUE THREAD

**Issue by Thibault-Poinsignon** [Thibault-Poinsignon/scere_explore#19]
The commands : `.__version__` and `.version` does not work for those two modules.

**Comment by pierrepo** [comment]
You can have a look to `notebooks/test_modules.ipynb`:
```
import matplotlib
print("Matplotlib:", matplotlib.__version__)
```
and
```
import plotly
print("plotly:", plotly.__version__)
```
The idea is to load the main module to get its version, no sub-module such as `pyplot` or `express`
