### ISSUE TITLE
Error upon creation of the database

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#21]
An error occurred upon creation of the database with the following command:
```
$ rm -rf data/ SCERE.db
$ bash download_SGD_data.sh
$ bash clean_data.sh
$ sqlite3 SCERE.db < schema_scere.sql
$ sqlite3 SCERE.db < import_SGD_data_to_tables.sql
[...]
./data/SGD/gene_association.sgd.gaf:33978: expected 16 columns but found 17 - extras ignored
./data/SGD/gene_association.sgd.gaf:33979: expected 16 columns but found 17 - extras ignored
./data/SGD/gene_association.sgd.gaf:33980: expected 16 columns but found 17 - extras ignored
./data/SGD/gene_association.sgd.gaf:33981: expected 16 columns but found 17 - extras ignored
./data/SGD/gene_association.sgd.gaf:33982: expected 16 columns but found 17 - extras ignored
[...]
```

Can you reproduce this error @Thibault-Poinsignon ?

**Comment by Thibault-Poinsignon** [comment]
Yes, and I identified its cause. The "gene_association.sgd.gaf" file was updated very recently :
![image](https://user-images.githubusercontent.com/73347912/108822281-27b04980-75bf-11eb-9784-c96eaabeb006.png)
The column 16 was replaced by two columns containing unclear information. I can fix this error by adapting the database schema.

**Comment by Thibault-Poinsignon** [comment]
I propose that will call the columns 16 and 17 "unknown_1" and "unknown_2" until the REALME is also updated. What do you think @pierrepo ?

**Comment by pierrepo** [comment]
>The "gene_association.sgd.gaf" file was updated very recently :

Thanks. I now understand why I had this error.

> I propose that will call the columns 16 and 17 "unknown_1" and "unknown_2"

You can also discard (delete) these columns if you feel they are not useful.

**Comment by Thibault-Poinsignon** [comment]
> You can also discard (delete) these columns if you feel they are not useful.

I would rather keep them until I know what they are.
