### ISSUE TITLE
Hover template not applied

### ISSUE THREAD

**Issue by Thibault-Poinsignon** [Thibault-Poinsignon/scere_explore#22]
In notebooks/chromosome_visualization.ipynb 'locus drawing' cell, the `hovertemplate` argument of the `Scatter` function is not applied.

**Comment by pierrepo** [comment]
Could you share here an excerpt of the code that is not working?

**Comment by pierrepo** [comment]
@Thibault-Poinsignon can you tell me if this code 
```
import plotly.express as px

df_2007 = px.data.gapminder().query("year==2007")

fig = px.scatter(df_2007, x="gdpPercap", y="lifeExp", log_x=True,
                 hover_name="country", hover_data=["continent", "pop"])

fig.show()
```
taken [here](https://plotly.com/python/hover-text-and-formatting/) is working for you?

**Comment by Thibault-Poinsignon** [comment]
Yes, this code is working for me.

**Comment by pierrepo** [comment]
:+1: 

Could you play with this code to implement the Hover?

**Comment by Thibault-Poinsignon** [comment]
I tried but it's the `plotly.express` function and i'm using the `plotly.graph_objects` one because it offers more options.
