### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by Thibault-Poinsignon** [Thibault-Poinsignon/scere_explore#23]
If all the chromosomes are represented in Plotly, the interactions with the figure are very slow.

**Comment by pierrepo** [comment]
How slow exactly?
What about if one or two chromosomes are displayed?

**Comment by Thibault-Poinsignon** [comment]
> How slow exactly?

Several seconds between an user input (click, drag, etc.) and its application.

> What about if one or two chromosomes are displayed?

With one or two chromosomes, the visualization is still usable.

**Comment by Thibault-Poinsignon** [comment]
There is the same problem with the 3D representation if the chromosomes are drawn as several lines (first step to represent the locus).

**Comment by Thibault-Poinsignon** [comment]
That could be a solution : https://www.somesolvedproblems.com/2019/05/how-to-make-plotly-faster-with-many.html

> A way around that is to add a NaN in between the point at the end of one line on the right and the beginning of the next line on the left.


It was not my first choice, because it complicate hover commands.

**Comment by Thibault-Poinsignon** [comment]
Putting all the traces in one `DataFrame` was indeed the solution, for the 3D representation at least. Now all the chromosomes (divided in ~500pb segments) can be visualized together without any lag.
