### ISSUE TITLE
2D visualization locus coloration

### ISSUE THREAD

**Issue by Thibault-Poinsignon** [Thibault-Poinsignon/scere_explore#26]
The `Scatter` function return an error when given an array of Integer as `Line Color` argument.
Same issue [here](https://stackoverflow.com/questions/58955557/python-plotly-scatter-specify-line-color-with-integer-value).

**Comment by Thibault-Poinsignon** [comment]
color is an array of integer values without any nan.

```
def GenomeDrawing(genome_data, parameter, color):
    
    color = genome_data[color].astype(int)
    color = np.array(color)
    
    fig = go.Figure(data=[go.Scatter(x= genome_data.Start_coordinate,
                                     y= genome_data.Stop_coordinate,
                                     mode='lines',
                                     line = {'color' : color,
                                             'width' : 10},
                                     name = "",
                                     customdata = genome_data,
                                     hovertemplate = "<b>Locus :</b> %{customdata[0]} <br>" + "<b>Chromosome :</b> %{customdata[4]} <br>",
                                     hoverlabel = dict(bgcolor="white", font_size=16),
                                    )])
    
    fig.update_layout(plot_bgcolor='white', xaxis_showgrid=False, yaxis_showgrid=False)
    fig.show()
```

**Comment by Thibault-Poinsignon** [comment]
According to the Plotly documentation for [2D scatter](https://plotly.com/python-api-reference/generated/plotly.graph_objects.scatter.html#plotly.graph_objects.scatter.Line) and [3D scatter](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.scatter3d.html#plotly.graph_objects.scatter3d.Line) `color` can be a number only in 3D.

**Comment by Thibault-Poinsignon** [comment]
@pierrepo can we easily transform an array of number into an array of "corresponding" color names ? (hex string, rgb/rgba string or CSS names)

**Comment by pierrepo** [comment]
> @pierrepo can we easily transform an array of number into an array of "corresponding" color names ? (hex string, rgb/rgba string or CSS names)

Yes, probably. We could discretize a color map.

**Comment by Thibault-Poinsignon** [comment]
I wrote a function which, for a given value, returns the corresponding rgba color name in the Viridis color scale.

It turns out that the `plotly.graph_objects.scatter.Line` does **not** take an array of color names for its color argument, contrary to the `plotly.graph_objects.scatter.Marker`.

So this was not the solution.

**Comment by pierrepo** [comment]
Ouch.... 

Can you please add links to the documentation @Thibault-Poinsignon ?

**Comment by Thibault-Poinsignon** [comment]
@pierrepo, here is the documentation :

- [plotly.graph_objects.scatter.Line](https://plotly.com/python-api-reference/generated/plotly.graph_objects.scatter.html#plotly.graph_objects.scatter.Line)

- [plotly.graph_objects.scatter.Marker](https://plotly.com/python-api-reference/generated/plotly.graph_objects.scatter.html#plotly.graph_objects.scatter.Marker)

**Comment by pierrepo** [comment]
Thanks.

Could you try using a `plotly.graph_objects.scatter.Marker` object with the `line` argument?

**Comment by Thibault-Poinsignon** [comment]
I'm currently exploring this possibility, but with no success so far : all my lines are staying red, instead of following the color-scale I'm setting.

**Comment by pierrepo** [comment]
Did you define `marker.cmin` and `marker.cmax`?

**Comment by Thibault-Poinsignon** [comment]
Yes, the function look like this :

`fig = go.Figure(go.Scatter(x = whole_genome.Start_coordinate,
                           y = whole_genome.Stop_coordinate,
                           mode ="lines",
                           marker_line_color = np.array(whole_genome.Chromosome.tolist()),
                           marker_line_colorscale = "Viridis",
                           marker_line_cmin = 1,
                           marker_line_cmax = 17,
                           line = {"width": 10},
                           name = "",
                           customdata = whole_genome,
                           hovertemplate = ("<b>Locus :</b> %{customdata[0]} <br>"
                                           "<b>Chromosome :</b> %{customdata[4]} <br>"),
                           hoverlabel = dict(bgcolor = "white", font_size = 16)))`

**Comment by Thibault-Poinsignon** [comment]
I think the `plotly.graph_objects.scatter.Marker.Line` argument is referring to the small edge around the markers...

**Comment by pierrepo** [comment]
Probably yes :cry: 

The fact you can have only one color for a `plotly.graph_objects.scatter.Line` object means that lines you were drawing were actually a single line but with spaces (inter loci, coded as `None`) in it. We probably have to create one `plotly.graph_objects.scatter.Line` object per locus. Every locus will then have a specific color but display will be much slower...

**Comment by Thibault-Poinsignon** [comment]
I succeeded whit `plotly.express` ! But It means I have to rework the way the chromosomes shapes and the hover are displayed...

![image](https://user-images.githubusercontent.com/73347912/111993816-59152a00-8b17-11eb-8cd2-ff13eca5ddbf.png)

**Comment by Thibault-Poinsignon** [comment]
> Every locus will then have a specific color but display will be much slower...

Yes, we would fall back into the issue with `add trace` again :/

Should I continue with `plotly.express` ?

**Comment by pierrepo** [comment]
> I succeeded whit plotly.express ! 

Awesome :star_struck:  How long does it take to display all loci of all chromosomes?

>Should I continue with plotly.express ?

Yes. This looks good.

**Comment by Thibault-Poinsignon** [comment]
> How long does it take to display all loci of all chromosomes?

447 ms !

**Comment by pierrepo** [comment]
> 447 ms !

:+1:

**Comment by pierrepo** [comment]
Any pic to conclude?

**Comment by Thibault-Poinsignon** [comment]
Nothing more than this one for now, I'm working on the grey background and the hover again.

![image](https://user-images.githubusercontent.com/73347912/112014021-d007ee00-8b2a-11eb-8af9-1c55a14e85fa.png)

**Comment by pierrepo** [comment]
Gorgeous. Thanks @Thibault-Poinsignon !

**Comment by Thibault-Poinsignon** [comment]
You are welcome @pierrepo  :)
