### ISSUE TITLE
Create independ repository for dashboard

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#27]
Hello @Thibault-Poinsignon 
Could you please create the new repo `scere_explore_dashboard` for the dashboard itself?

Could you then give me permissions to edit this repo?

**Comment by pierrepo** [comment]
Hey @Thibault-Poinsignon 
I've created the repo in our `data-fun` GitHub organization https://github.com/data-fun/3d-scere
You should have received an invitation with write access to the repo.
Could you please populate this repo with files related to the dashboard?

**Comment by Thibault-Poinsignon** [comment]
Hey @pierrepo, I added the files needed for the dashboard. Several updates are necessary, I put them in the "project" tab.

**Comment by pierrepo** [comment]
OK. thanks @Thibault-Poinsignon 

Could you also, please document the way you run the dashboard in the README file?
