### ISSUE TITLE
Create conda environment

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#4]
It's a good practice to create a dedicated conda environment for every project.

@Thibault-Poinsignon could you create a file `environment.yml` that contains all dependencies for the project?

Both sqlite and db-brower are available in conda:

```
conda install -c conda-forge sqlite
conda install -c bioconda sqlitebrowser
```

**Comment by Thibault-Poinsignon** [comment]
I created the .yml file with this command :
`conda env export > SCERES_env.yml`

What is the command that create a more synthesized file ?

**Comment by pierrepo** [comment]
I rather advise to build it my hand.
