### ISSUE TITLE
Improve SGD data download

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#5]
## Naming

Since `download_SGD_data.sh` and `download_SGD_readme.sh` both download data from the SGD. They should be merged into a single bash script (for instance `download_SGD_data.sh`). All data and README should go into `SGD_data`

## Download output dir

There is not need to `cd` into the target `SGD_data` directory since `-P` of `wget` specifies and output directory.
For instance:
```
wget -P SGD_data http://sgd-archive.yeastgenome.org/curation/chromosomal_feature/SGD_features.tab
```

## Run script

Always try to be explicit with what interpreter your run, whether it is a Bash, R or Python script. For instance:
```
bash my_bash_script.sh
python my_python_script.py
Rscript my_r_script.R
```
For the present case, this could be:
```
bash download_SGD_data.sh
```

**Comment by Thibault-Poinsignon** [comment]
I separated the readme into a sub file SGD_data/SGD_readme for more clarity. What do you think ?

**Comment by pierrepo** [comment]
I think we should have something like that:
```
data
└── SGD
```
with everything downloaded from the SGD inside.
