### ISSUE TITLE
Create a data cleaning script

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/scere_explore#6]
It would be interesting to pull all data cleaning steps: 
```
gzip -d ./SGD_data/gene_association.sgd.gaf.gz
sed -i '/^!/d' ./SGD_data/gene_association.sgd.gaf
sed -i s/\"//g ./SGD_data/phenotype_data.tab
sed -i '1d' protein_properties.tab
```
into a bash script (for instance `clean_data.sh`)

**Comment by pierrepo** [comment]
Nice Nature article on command line and bash scripting:

https://www.nature.com/articles/d41586-021-00263-0

With many examples here: https://github.com/jperkel/nature_bash/

**Comment by pierrepo** [comment]
By the way, always add 
```
set -euo pipefail 
```
on the top of your bash scripts.

With explanations here: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

**Comment by pierrepo** [comment]
Please explain what you are doing on each file / line (use comments from README.md file)

**Comment by Thibault-Poinsignon** [comment]
What do you think of the new clean_data.sh ?
